version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/apps/python"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/apps/ruby"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/apps/go"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/apps/rust"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "pip"
    directory: "/apps/python"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "bundler"
    directory: "/apps/ruby"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "cargo"
    directory: "/apps/rust"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
